# Generated by Django 3.2.8 on 2021-10-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=50, verbose_name='Alergia')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100, verbose_name='Diagnóstico')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100, verbose_name='Dieta')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('ext', models.CharField(max_length=10, verbose_name='No. Exterior')),
                ('int', models.CharField(max_length=10, verbose_name='No. Interior')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Edad')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('cur', models.CharField(max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=12, verbose_name='RFC')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=10, verbose_name='cedula')),
                ('photo', models.ImageField(null=True, upload_to='imgMedicos', verbose_name='Agregar Foto')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('birthday', models.DateTimeField()),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Edad')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('cur', models.CharField(max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=12, verbose_name='RFC')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direction', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergy', verbose_name='Alergia')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosis', verbose_name='Diagnóstico')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diet', verbose_name='Dieta')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic', verbose_name='Médico')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.CharField(max_length=50, verbose_name='Laboratorio')),
                ('date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.AddField(
            model_name='diet',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='diet',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic', verbose_name='Médico')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.AddField(
            model_name='allergy',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente'),
        ),
    ]
