# Generated by Django 3.2.8 on 2021-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('birthday', models.CharField(max_length=11, verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
