# Generated by Django 3.2.8 on 2021-10-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('laboratory', models.CharField(max_length=50, verbose_name='Laboratorio')),
                ('expiration', models.CharField(max_length=10, verbose_name='Caducidad')),
            ],
        ),
    ]
