# Generated by Django 3.2.8 on 2021-10-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicina', 'verbose_name_plural': 'Medicinas'},
        ),
    ]
