# Generated by Django 3.2.8 on 2021-10-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211014_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Servicio')),
                ('laboratory', models.CharField(max_length=50, verbose_name='Laboratorio')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Medicina',
                'verbose_name_plural': 'Medicinas',
            },
        ),
    ]
