# Generated by Django 3.2.8 on 2021-10-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='laboratory',
            field=models.CharField(max_length=50, verbose_name='Áreas'),
        ),
    ]
