# Generated by Django 3.2.8 on 2021-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_service_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
