# Generated by Django 3.2.8 on 2021-10-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(null=True, upload_to='imgServicios', verbose_name='Agregar Foto'),
        ),
    ]
